
// Generated by 'transfrom'
/* eslint-disable */

import __codesandbox from './items/codesandbox';

import __weibosquare from './items/weibosquare';

import __weibocircle from './items/weibocircle';

import __taobaocircle from './items/taobaocircle';

import __html from './items/html';

import __weibo from './items/weibo';

import __twitter from './items/twitter';

import __wechat from './items/wechat';

import __youtube from './items/youtube';

import __alipaycircle from './items/alipaycircle';

import __taobaosquare from './items/taobaosquare';

import __skype from './items/skype';

import __qq from './items/qq';

import __mediumwordmark from './items/mediumwordmark';

import __gitlab from './items/gitlab';

import __mediummonogram from './items/mediummonogram';

import __linkedinsquare from './items/linkedinsquare';

import __googleplus from './items/googleplus';

import __dropbox from './items/dropbox';

import __facebooksquare from './items/facebooksquare';

import __codepen from './items/codepen';

import __amazon from './items/amazon';

import __google from './items/google';

import __codepencircle from './items/codepencircle';

import __alipaysquare from './items/alipaysquare';

import __antdesign from './items/antdesign';

import __menufold from './items/menufold';

import __menuunfold from './items/menuunfold';

import __indentright from './items/indentright';

import __indentleft from './items/indentleft';

import __dashboard from './items/dashboard';

import __profile from './items/profile';

import __table from './items/table';

import __warning from './items/warning';

import __form from './items/form';

import __edit from './items/edit';

import __fork from './items/fork';

import __solution from './items/solution';

import __contacts from './items/contacts';

import __exception from './items/exception';

import __scan from './items/scan';

import __appstore from './items/appstore';

import __appstoreo from './items/appstoreo';

import __api from './items/api';

import __shake from './items/shake';

import __message from './items/message';

import __reload from './items/reload';

import __logout from './items/logout';

import __login from './items/login';

import __sync from './items/sync';

import __wifi from './items/wifi';

import __earth from './items/earth';

import __sound from './items/sound';

import __copyright from './items/copyright';

import __find from './items/find';

import __trademark from './items/trademark';

import __poweroff from './items/poweroff';

import __paycircleo from './items/paycircleo';

import __paycircle from './items/paycircle';

import __aliwangwang from './items/aliwangwang';

import __aliwangwango from './items/aliwangwango';

import __android from './items/android';

import __appleo from './items/appleo';

import __apple from './items/apple';

import __select from './items/select';

import __rocket from './items/rocket';

import __bulb from './items/bulb';

import __dislike from './items/dislike';

import __like from './items/like';

import __dislike2 from './items/dislike2';

import __like2 from './items/like2';

import __loading2 from './items/loading2';

import __loading from './items/loading';

import __trophy from './items/trophy';

import __bank from './items/bank';

import __adduser from './items/adduser';

import __woman from './items/woman';

import __wallet from './items/wallet';

import __safety from './items/safety';

import __rest from './items/rest';

import __redenvelopes from './items/redenvelopes';

import __medicinebox from './items/medicinebox';

import __idcard from './items/idcard';

import __gift from './items/gift';

import __isv from './items/isv';

import __man from './items/man';

import __deleteusergroup from './items/deleteusergroup';

import __deleteuser from './items/deleteuser';

import __carryout from './items/carryout';

import __addusergroup from './items/addusergroup';

import __car from './items/car';

import __tool from './items/tool';

import __skin from './items/skin';

import __usb from './items/usb';

import __printer from './items/printer';

import __layout from './items/layout';

import __flag from './items/flag';

import __key from './items/key';

import __hourglass from './items/hourglass';

import __barcode from './items/barcode';

import __database from './items/database';

import __disconnect from './items/disconnect';

import __bells from './items/bells';

import __tablet from './items/tablet';

import __mobile from './items/mobile';

import __dingdingo from './items/dingdingo';

import __dingding from './items/dingding';

import __wordfile from './items/wordfile';

import __unknowfile from './items/unknowfile';

import __pptfile from './items/pptfile';

import __exclefile from './items/exclefile';

import __pdffile from './items/pdffile';

import __jpgfile from './items/jpgfile';

import __copy from './items/copy';

import __filetext from './items/filetext';

import __calendar from './items/calendar';

import __ellipsis from './items/ellipsis';

import __search from './items/search';

import __file from './items/file';

import __folderopen from './items/folderopen';

import __addfolder from './items/addfolder';

import __switcher from './items/switcher';

import __folder from './items/folder';

import __addfile from './items/addfile';

import __tago from './items/tago';

import __tag from './items/tag';

import __playcircleo from './items/playcircleo';

import __play from './items/play';

import __upsquareo from './items/upsquareo';

import __downsquareo from './items/downsquareo';

import __leftsquareo from './items/leftsquareo';

import __rightsquareo from './items/rightsquareo';

import __rightsquare from './items/rightsquare';

import __leftsquare from './items/leftsquare';

import __downsquare from './items/downsquare';

import __upsquare from './items/upsquare';

import __fastforward from './items/fastforward';

import __fastbackward from './items/fastbackward';

import __checksquareo from './items/checksquareo';

import __checksquare from './items/checksquare';

import __closesquareo from './items/closesquareo';

import __closesquare from './items/closesquare';

import __minussquare from './items/minussquare';

import __plussquare from './items/plussquare';

import __codesquare from './items/codesquare';

import __barchart from './items/barchart';

import __dotchart from './items/dotchart';

import __windowso from './items/windowso';

import __unlock from './items/unlock';

import __lock from './items/lock';

import __piechart from './items/piechart';

import __download from './items/download';

import __upload from './items/upload';

import __caretcircleoup from './items/caretcircleoup';

import __iconfontdesktop from './items/iconfontdesktop';

import __github from './items/github';

import __chrome from './items/chrome';

import __calculator from './items/calculator';

import __frowno from './items/frowno';

import __smileo from './items/smileo';

import __smilecircle from './items/smilecircle';

import __hearto from './items/hearto';

import __heart from './items/heart';

import __pushpin from './items/pushpin';

import __pushpino from './items/pushpino';

import __enter from './items/enter';

import __delete from './items/delete';

import __ie from './items/ie';

import __hdd from './items/hdd';

import __circledown from './items/circledown';

import __circledowno from './items/circledowno';

import __export from './items/export';

import __export2 from './items/export2';

import __windows from './items/windows';

import __camerao from './items/camerao';

import __camera from './items/camera';

import __eyeo from './items/eyeo';

import __eye from './items/eye';

import __enviromento from './items/enviromento';

import __enviroment from './items/enviroment';

import __clouduploado from './items/clouduploado';

import __clouddownloado from './items/clouddownloado';

import __clouddownload from './items/clouddownload';

import __cloudupload from './items/cloudupload';

import __cloud from './items/cloud';

import __cloudo from './items/cloudo';

import __tagso from './items/tagso';

import __tags from './items/tags';

import __qrcode from './items/qrcode';

import __inbox from './items/inbox';

import __notification from './items/notification';

import __paperclip from './items/paperclip';

import __phone from './items/phone';

import __picture from './items/picture';

import __setting from './items/setting';

import __sharealt from './items/sharealt';

import __team from './items/team';

import __totop from './items/totop';

import __videocamera from './items/videocamera';

import __user from './items/user';

import __save from './items/save';

import __shoppingcart from './items/shoppingcart';

import __meh from './items/meh';

import __meho from './items/meho';

import __filter from './items/filter';

import __staro from './items/staro';

import __star from './items/star';

import __laptop from './items/laptop';

import __home from './items/home';

import __linechart from './items/linechart';

import __areachart from './items/areachart';

import __link from './items/link';

import __mail from './items/mail';

import __frown from './items/frown';

import __plussquareo from './items/plussquareo';

import __swapright from './items/swapright';

import __swapleft from './items/swapleft';

import __swap from './items/swap';

import __clockcircleo from './items/clockcircleo';

import __clockcircle from './items/clockcircle';

import __pausecircleo from './items/pausecircleo';

import __pausecircle from './items/pausecircle';

import __pause from './items/pause';

import __questioncircleo from './items/questioncircleo';

import __questioncircle from './items/questioncircle';

import __question from './items/question';

import __bars from './items/bars';

import __barschart from './items/barschart';

import __book from './items/book';

import __codesquareo from './items/codesquareo';

import __creditcard from './items/creditcard';

import __customerservice from './items/customerservice';

import __close from './items/close';

import __check from './items/check';

import __checkcircleo from './items/checkcircleo';

import __checkcircle from './items/checkcircle';

import __closecircleo from './items/closecircleo';

import __closecircle from './items/closecircle';

import __exclamationcircleo from './items/exclamationcircleo';

import __exclamationcircle from './items/exclamationcircle';

import __exclamation from './items/exclamation';

import __info from './items/info';

import __infocirlceo from './items/infocirlceo';

import __infocirlce from './items/infocirlce';

import __plus from './items/plus';

import __pluscircle from './items/pluscircle';

import __pluscircleo from './items/pluscircleo';

import __minus from './items/minus';

import __minuscircleo from './items/minuscircleo';

import __minuscircle from './items/minuscircle';

import __minussquareo from './items/minussquareo';

import __left from './items/left';

import __right from './items/right';

import __up from './items/up';

import __down from './items/down';

import __arrowleft from './items/arrowleft';

import __arrowright from './items/arrowright';

import __arrowup from './items/arrowup';

import __arrowdown from './items/arrowdown';

import __doubleleft from './items/doubleleft';

import __doubleright from './items/doubleright';

import __arrowsalt from './items/arrowsalt';

import __shrink from './items/shrink';

import __retweet from './items/retweet';

import __back from './items/back';

import __verticleright from './items/verticleright';

import __verticleleft from './items/verticleleft';

import __downcircleo from './items/downcircleo';

import __upcircleo from './items/upcircleo';

import __leftcircleo from './items/leftcircleo';

import __rightcircleo from './items/rightcircleo';

import __downcircle from './items/downcircle';

import __upcircle from './items/upcircle';

import __leftcircle from './items/leftcircle';

import __rightcircle from './items/rightcircle';

import __caretup from './items/caretup';

import __caretdown from './items/caretdown';

import __caretleft from './items/caretleft';

import __caretright from './items/caretright';

import __banckward from './items/banckward';

import __forward from './items/forward';

import __stepbackward from './items/stepbackward';

import __stepforward from './items/stepforward';


export default {

  codesandbox: __codesandbox,
  weibosquare: __weibosquare,
  weibocircle: __weibocircle,
  taobaocircle: __taobaocircle,
  html: __html,
  weibo: __weibo,
  twitter: __twitter,
  wechat: __wechat,
  youtube: __youtube,
  alipaycircle: __alipaycircle,
  taobaosquare: __taobaosquare,
  skype: __skype,
  qq: __qq,
  mediumwordmark: __mediumwordmark,
  gitlab: __gitlab,
  mediummonogram: __mediummonogram,
  linkedinsquare: __linkedinsquare,
  googleplus: __googleplus,
  dropbox: __dropbox,
  facebooksquare: __facebooksquare,
  codepen: __codepen,
  amazon: __amazon,
  google: __google,
  codepencircle: __codepencircle,
  alipaysquare: __alipaysquare,
  antdesign: __antdesign,
  menufold: __menufold,
  menuunfold: __menuunfold,
  indentright: __indentright,
  indentleft: __indentleft,
  dashboard: __dashboard,
  profile: __profile,
  table: __table,
  warning: __warning,
  form: __form,
  edit: __edit,
  fork: __fork,
  solution: __solution,
  contacts: __contacts,
  exception: __exception,
  scan: __scan,
  appstore: __appstore,
  appstoreo: __appstoreo,
  api: __api,
  shake: __shake,
  message: __message,
  reload: __reload,
  logout: __logout,
  login: __login,
  sync: __sync,
  wifi: __wifi,
  earth: __earth,
  sound: __sound,
  copyright: __copyright,
  find: __find,
  trademark: __trademark,
  poweroff: __poweroff,
  paycircleo: __paycircleo,
  paycircle: __paycircle,
  aliwangwang: __aliwangwang,
  aliwangwango: __aliwangwango,
  android: __android,
  appleo: __appleo,
  apple: __apple,
  select: __select,
  rocket: __rocket,
  bulb: __bulb,
  dislike: __dislike,
  like: __like,
  dislike2: __dislike2,
  like2: __like2,
  loading2: __loading2,
  loading: __loading,
  trophy: __trophy,
  bank: __bank,
  adduser: __adduser,
  woman: __woman,
  wallet: __wallet,
  safety: __safety,
  rest: __rest,
  redenvelopes: __redenvelopes,
  medicinebox: __medicinebox,
  idcard: __idcard,
  gift: __gift,
  isv: __isv,
  man: __man,
  deleteusergroup: __deleteusergroup,
  deleteuser: __deleteuser,
  carryout: __carryout,
  addusergroup: __addusergroup,
  car: __car,
  tool: __tool,
  skin: __skin,
  usb: __usb,
  printer: __printer,
  layout: __layout,
  flag: __flag,
  key: __key,
  hourglass: __hourglass,
  barcode: __barcode,
  database: __database,
  disconnect: __disconnect,
  bells: __bells,
  tablet: __tablet,
  mobile: __mobile,
  dingdingo: __dingdingo,
  dingding: __dingding,
  wordfile: __wordfile,
  unknowfile: __unknowfile,
  pptfile: __pptfile,
  exclefile: __exclefile,
  pdffile: __pdffile,
  jpgfile: __jpgfile,
  copy: __copy,
  filetext: __filetext,
  calendar: __calendar,
  ellipsis: __ellipsis,
  search: __search,
  file: __file,
  folderopen: __folderopen,
  addfolder: __addfolder,
  switcher: __switcher,
  folder: __folder,
  addfile: __addfile,
  tago: __tago,
  tag: __tag,
  playcircleo: __playcircleo,
  play: __play,
  upsquareo: __upsquareo,
  downsquareo: __downsquareo,
  leftsquareo: __leftsquareo,
  rightsquareo: __rightsquareo,
  rightsquare: __rightsquare,
  leftsquare: __leftsquare,
  downsquare: __downsquare,
  upsquare: __upsquare,
  fastforward: __fastforward,
  fastbackward: __fastbackward,
  checksquareo: __checksquareo,
  checksquare: __checksquare,
  closesquareo: __closesquareo,
  closesquare: __closesquare,
  minussquare: __minussquare,
  plussquare: __plussquare,
  codesquare: __codesquare,
  barchart: __barchart,
  dotchart: __dotchart,
  windowso: __windowso,
  unlock: __unlock,
  lock: __lock,
  piechart: __piechart,
  download: __download,
  upload: __upload,
  caretcircleoup: __caretcircleoup,
  iconfontdesktop: __iconfontdesktop,
  github: __github,
  chrome: __chrome,
  calculator: __calculator,
  frowno: __frowno,
  smileo: __smileo,
  smilecircle: __smilecircle,
  hearto: __hearto,
  heart: __heart,
  pushpin: __pushpin,
  pushpino: __pushpino,
  enter: __enter,
  delete: __delete,
  ie: __ie,
  hdd: __hdd,
  circledown: __circledown,
  circledowno: __circledowno,
  export: __export,
  export2: __export2,
  windows: __windows,
  camerao: __camerao,
  camera: __camera,
  eyeo: __eyeo,
  eye: __eye,
  enviromento: __enviromento,
  enviroment: __enviroment,
  clouduploado: __clouduploado,
  clouddownloado: __clouddownloado,
  clouddownload: __clouddownload,
  cloudupload: __cloudupload,
  cloud: __cloud,
  cloudo: __cloudo,
  tagso: __tagso,
  tags: __tags,
  qrcode: __qrcode,
  inbox: __inbox,
  notification: __notification,
  paperclip: __paperclip,
  phone: __phone,
  picture: __picture,
  setting: __setting,
  sharealt: __sharealt,
  team: __team,
  totop: __totop,
  videocamera: __videocamera,
  user: __user,
  save: __save,
  shoppingcart: __shoppingcart,
  meh: __meh,
  meho: __meho,
  filter: __filter,
  staro: __staro,
  star: __star,
  laptop: __laptop,
  home: __home,
  linechart: __linechart,
  areachart: __areachart,
  link: __link,
  mail: __mail,
  frown: __frown,
  plussquareo: __plussquareo,
  swapright: __swapright,
  swapleft: __swapleft,
  swap: __swap,
  clockcircleo: __clockcircleo,
  clockcircle: __clockcircle,
  pausecircleo: __pausecircleo,
  pausecircle: __pausecircle,
  pause: __pause,
  questioncircleo: __questioncircleo,
  questioncircle: __questioncircle,
  question: __question,
  bars: __bars,
  barschart: __barschart,
  book: __book,
  codesquareo: __codesquareo,
  creditcard: __creditcard,
  customerservice: __customerservice,
  close: __close,
  check: __check,
  checkcircleo: __checkcircleo,
  checkcircle: __checkcircle,
  closecircleo: __closecircleo,
  closecircle: __closecircle,
  exclamationcircleo: __exclamationcircleo,
  exclamationcircle: __exclamationcircle,
  exclamation: __exclamation,
  info: __info,
  infocirlceo: __infocirlceo,
  infocirlce: __infocirlce,
  plus: __plus,
  pluscircle: __pluscircle,
  pluscircleo: __pluscircleo,
  minus: __minus,
  minuscircleo: __minuscircleo,
  minuscircle: __minuscircle,
  minussquareo: __minussquareo,
  left: __left,
  right: __right,
  up: __up,
  down: __down,
  arrowleft: __arrowleft,
  arrowright: __arrowright,
  arrowup: __arrowup,
  arrowdown: __arrowdown,
  doubleleft: __doubleleft,
  doubleright: __doubleright,
  arrowsalt: __arrowsalt,
  shrink: __shrink,
  retweet: __retweet,
  back: __back,
  verticleright: __verticleright,
  verticleleft: __verticleleft,
  downcircleo: __downcircleo,
  upcircleo: __upcircleo,
  leftcircleo: __leftcircleo,
  rightcircleo: __rightcircleo,
  downcircle: __downcircle,
  upcircle: __upcircle,
  leftcircle: __leftcircle,
  rightcircle: __rightcircle,
  caretup: __caretup,
  caretdown: __caretdown,
  caretleft: __caretleft,
  caretright: __caretright,
  banckward: __banckward,
  forward: __forward,
  stepbackward: __stepbackward,
  stepforward: __stepforward
}
