
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1025 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="banckward" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M448.975 106.1 12.675 481.6c-16.9 15.7-16.9 43.3 0 59l436.2 377.3c24.4 22.8 63.1 4.7 63.1-29.5L511.975 511.1 511.975 135.6C512.075 101.5 473.375 83.4 448.975 106.1zM960.975 106.1 524.675 481.6c-8.4 7.9-12.6 18.7-12.6 29.5s4.2 21.6 12.6 29.5l436.2 377.3c24.4 22.8 63.1 4.7 63.1-29.5L1023.975 135.6C1024.075 101.5 985.375 83.4 960.975 106.1z"
      p-id="9214" />
  </Svg>
)
