
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="barchart" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M923 960 99 960c-19.9 0-36-16.1-36-36L63 100c0-19.9 16.1-36 36-36s36 16.1 36 36l0 788 788 0c19.9 0 36 16.1 36 36S942.9 960 923 960zM264.2 373c-39.3 0.9-71.4 33.1-72.2 72.4-0.6 30.1 16.7 56.2 42 68.3L234 799c0 17.7 14.3 32 32 32l0 0c17.7 0 32-14.3 32-32L298 513.7c24.8-11.9 42-37.3 42-66.7C340 405.5 305.9 372 264.2 373zM541.7 255c-39.3 0.9-71.4 33.1-72.2 72.4-0.6 30.1 16.7 56.2 42 68.3L511.5 799c0 17.7 14.3 32 32 32l0 0c17.7 0 32-14.3 32-32L575.5 395.7c24.8-11.9 42-37.3 42-66.7C617.5 287.5 583.4 254 541.7 255zM895 458c0-41.5-34.1-75-75.8-74-39.3 0.9-71.4 33.1-72.2 72.4-0.6 30.1 16.7 56.2 42 68.3L789 799c0 17.7 14.3 32 32 32l0 0c17.7 0 32-14.3 32-32L853 524.7C877.8 512.8 895 487.4 895 458z"
      p-id="5241" />
  </SvgContainer>
)
