
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp-compatible';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="bars" width={ props.width || 16 } height={ props.height || 16 } fill={ props.fill || "#666" }>
    <Path d="M186.8 256.8m-63 0a63 63 0 1 0 126 0 63 63 0 1 0-126 0ZM855.7 285.8 357.9 285.8c-19.9 0-36.1-16.2-36.1-36.1l0 0c0-19.9 16.2-36.1 36.1-36.1l497.9 0c19.9 0 36.1 16.2 36.1 36.1l0 0C891.8 269.7 875.7 285.8 855.7 285.8zM186.8 512m-63 0a63 63 0 1 0 126 0 63 63 0 1 0-126 0ZM855.7 541.1 357.9 541.1c-19.9 0-36.1-16.2-36.1-36.1l0 0c0-19.9 16.2-36.1 36.1-36.1l497.9 0c19.9 0 36.1 16.2 36.1 36.1l0 0C891.8 524.9 875.7 541.1 855.7 541.1zM186.8 767.2m-63 0a63 63 0 1 0 126 0 63 63 0 1 0-126 0ZM855.7 796.3 357.9 796.3c-19.9 0-36.1-16.2-36.1-36.1l0 0c0-19.9 16.2-36.1 36.1-36.1l497.9 0c19.9 0 36.1 16.2 36.1 36.1l0 0C891.8 780.2 875.7 796.3 855.7 796.3z"
      p-id="7677" />
  </Svg>
)
