
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="bells" width={ props.width || 16 } height={ props.height || 16 } fill={ props.fill || "#666" }>
    <Path d="M860 832h-28V384c0-164.6-124.2-300.1-284-318V36c0-19.9-16.1-36-36-36s-36 16.1-36 36v30C316.2 83.9 192 219.4 192 384v448h-28c-19.9 0-36 16.1-36 36s16.1 36 36 36h276v48c0 39.8 32.2 72 72 72s72-32.2 72-72v-48h276c19.9 0 36-16.1 36-36s-16.1-36-36-36z m-100 0H264V384c0-137 111-248 248-248s248 111 248 248v448z"
      p-id="3992" />
  </Svg>
)
