
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="clockcircle" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M512 0C229.2 0 0 229.2 0 512s229.2 512 512 512 512-229.2 512-512S794.8 0 512 0zM769 540c0 19.9-16.1 36-36 36L548 576l0 0c-39.8 0-72-32.2-72-72l0 0L476 264c0-19.9 16.1-36 36-36l0 0c19.9 0 36 16.1 36 36l0 240 185 0C752.9 504 769 520.1 769 540L769 540z"
      p-id="7474" />
  </Svg>
)
