
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="database" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M824 0H200c-39.8 0-72 32.2-72 72v880c0 39.8 32.2 72 72 72h624c39.8 0 72-32.2 72-72V72c0-39.8-32.2-72-72-72z m0 943H200V699c0 0.5 0.4 1 1 1h622c0.5 0 1-0.4 1-1v244z m0-314c0-0.5-0.4-1-1-1H201c-0.5 0-1 0.4-1 1V385c0 0.5 0.4 1 1 1h622c0.5 0 1-0.4 1-1v244z m0-314c0-0.5-0.4-1-1-1H201c-0.5 0-1 0.4-1 1V72h624v243zM321 821m-36 0a36 36 0 1 0 72 0 36 36 0 1 0-72 0ZM321 507m-36 0a36 36 0 1 0 72 0 36 36 0 1 0-72 0ZM321 193m-36 0a36 36 0 1 0 72 0 36 36 0 1 0-72 0Z"
      p-id="3934" />
  </Svg>
)
