
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp-compatible';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="exception1" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M888 64H135c-39.7 0-72 32.3-72 72v752c0 39.7 32.3 72 72 72h277c19.9 0 36-16.1 36-36s-16.1-36-36-36H135V136h753v752h-84c-19.9 0-36 16.1-36 36s16.1 36 36 36h84c39.7 0 72-32.3 72-72V136c0-39.7-32.3-72-72-72z"
      p-id="2125" />
    <Path d="M676 924m-36 0a36 36 0 1 0 72 0 36 36 0 1 0-72 0Z" p-id="2126" />
    <Path d="M676 384c-19.9 0-36 16.1-36 36v376c0 19.9 16.1 36 36 36s36-16.1 36-36V420c0-19.9-16.1-36-36-36zM540 256H228c-19.9 0-36 16.1-36 36s16.1 36 36 36h312c19.9 0 36-16.1 36-36s-16.1-36-36-36zM412 448H228c-19.9 0-36 16.1-36 36s16.1 36 36 36h184c19.9 0 36-16.1 36-36s-16.1-36-36-36zM412 640H228c-19.9 0-36 16.1-36 36s16.1 36 36 36h184c19.9 0 36-16.1 36-36s-16.1-36-36-36z"
      p-id="2127" />
  </Svg>
)
