
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="exclamation" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M512 703c-22.1 0-40-17.9-40-40L472 168c0-22.1 17.9-40 40-40 22.1 0 40 17.9 40 40l0 495C552 685.1 534.1 703 512 703zM512 813m-45 0a45 45 0 1 0 90 0 45 45 0 1 0-90 0Z"
      p-id="8083" />
  </Svg>
)
