
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="find" width={ props.width || 16 } height={ props.height || 16 } fill={ props.fill || "#666" }>
    <Path d="M521.3 384.3c-35.8-2.6-72.5 9.8-99.8 37.2-27.4 27.4-39.8 64-37.2 99.8l-98.6 216.9 216.9-98.6c35.8 2.6 72.5-9.8 99.8-37.2 27.4-27.4 39.8-64 37.2-99.8l98.6-216.9-216.9 98.6z m30.3 167.3c-21.9 21.9-57.3 21.9-79.2 0-21.9-21.9-21.9-57.3 0-79.2 21.9-21.9 57.3-21.9 79.2 0 21.9 21.9 21.9 57.3 0 79.2zM512 0C229.2 0 0 229.2 0 512s229.2 512 512 512 512-229.2 512-512S794.8 0 512 0z m0 952C269 952 72 755 72 512S269 72 512 72s440 197 440 440-197 440-440 440z"
      p-id="2565" />
  </Svg>
)
