
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="forward" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M575.1 106.1l436.2 375.4c16.9 15.7 16.9 43.3 0 59L575.1 917.9c-24.4 22.8-63.1 4.7-63.1-29.5l0-377.3L512 135.6C512 101.5 550.7 83.4 575.1 106.1zM63.1 106.1l436.2 375.4c8.4 7.9 12.6 18.7 12.6 29.5 0 10.8-4.2 21.6-12.6 29.5L63.1 917.9C38.7 940.6 0 922.5 0 888.4l0-752.7C0 101.5 38.7 83.4 63.1 106.1z"
      p-id="9243" />
  </SvgContainer>
)
