
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="info" width={ props.width || 16 } height={ props.height || 16 } fill={ props.fill || "#666" }>
    <Path d="M660.2 759.6 575 759.6 575 355.5c0-19.9-16.1-36-36-36l0 0-36 0-60 0c-19.9 0-36 16.1-36 36l0 0c0 19.9 16.1 36 36 36l60 0 0 368.1-85.2 0c-19.9 0-36 16.1-36 36l0 0c0 19.9 16.1 36 36 36L503 831.6l72 0 85.2 0c19.9 0 36-16.1 36-36l0 0C696.2 775.7 680.1 759.6 660.2 759.6zM539 220.5m-36 0a36 36 0 1 0 72 0 36 36 0 1 0-72 0Z"
      p-id="8112" />
  </SvgContainer>
)
