
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="leftsquareo" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M888.5 135.5 888.5 135.5 888.5 135.5l0 753.1 0 0-753 0 0 0L135.5 135.5l0 0L888.5 135.5M888.5 63.5l-753 0c-39.8 0-72 32.2-72 72l0 753.1c0 39.8 32.2 72 72 72l753.1 0c39.8 0 72-32.2 72-72L960.6 135.5C960.5 95.7 928.3 63.5 888.5 63.5L888.5 63.5zM331.3 538.2l235.8 221c14.5 13.6 37.3 12.9 50.9-1.6 13.6-14.5 12.9-37.3-1.6-50.9L408.7 512l207.8-194.8c14.5-13.6 15.2-36.4 1.6-50.9-13.6-14.5-36.4-15.2-50.9-1.6l-235.8 221C324.1 492.5 320 502 320 512S324.1 531.5 331.3 538.2z"
      p-id="4806" />
  </SvgContainer>
)
