
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="medicinebox" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M952 312H832V200c0-39.8-32.2-72-72-72H264c-39.8 0-72 32.2-72 72v112H72c-39.8 0-72 32.2-72 72v440c0 39.8 32.2 72 72 72h880c39.8 0 72-32.2 72-72V384c0-39.8-32.2-72-72-72zM264 200h496v112H264V200z m688 624H72V384h880v440zM388 640h88v88c0 19.9 16.1 36 36 36s36-16.1 36-36v-88h88c19.9 0 36-16.1 36-36s-16.1-36-36-36h-88v-88c0-19.9-16.1-36-36-36s-36 16.1-36 36v88h-88c-19.9 0-36 16.1-36 36s16.1 36 36 36z"
      p-id="3383" />
  </Svg>
)
