
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="minussquareo" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M888.5 135.5 888.5 135.5 888.5 135.5l0 753.1 0 0-753 0 0 0L135.5 135.5l0 0L888.5 135.5M888.5 63.5l-753 0c-39.8 0-72 32.2-72 72l0 753.1c0 39.8 32.2 72 72 72l753.1 0c39.8 0 72-32.2 72-72L960.6 135.5C960.5 95.7 928.3 63.5 888.5 63.5L888.5 63.5zM731.5 549l-441 0c-19.9 0-36-16.1-36-36l0 0c0-19.9 16.1-36 36-36l441 0c19.9 0 36 16.1 36 36l0 0C767.5 532.9 751.4 549 731.5 549z"
      p-id="8373" />
  </SvgContainer>
)
