
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="minuscircle" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M512 0C229.2 0 0 229.2 0 512s229.2 512 512 512 512-229.2 512-512S794.8 0 512 0zM832.5 512c0 19.9-16.1 36-36 36l-569 0c-19.9 0-36-16.1-36-36l0 0c0-19.9 16.1-36 36-36l569 0C816.4 476 832.5 492.1 832.5 512L832.5 512z"
      p-id="8344" />
  </SvgContainer>
)
