
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="minus" width={ props.width || 16 } height={ props.height || 16 } fill={ props.fill || "#666" }>
    <Path d="M796.5 548l-569 0c-19.9 0-36-16.1-36-36l0 0c0-19.9 16.1-36 36-36l569 0c19.9 0 36 16.1 36 36l0 0C832.5 531.9 816.4 548 796.5 548z" p-id="8286" />
  </SvgContainer>
)
