
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp-compatible';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="pause" width={ props.width || 16 } height={ props.height || 16 } fill={ props.fill || "#666" }>
    <Path d="M325.5 192.5 325.5 192.5c-19.9 0-36 16.1-36 36l0 567c0 19.9 16.1 36 36 36l0 0c19.9 0 36-16.1 35-36l0-567C361.5 208.6 345.4 192.5 325.5 192.5zM698.5 192.5 698.5 192.5c-19.9 0-36 16.1-36 36l0 567c0 19.9 16.1 36 36 36l0 0c19.9 0 36-16.1 36-36l0-567C734.5 208.6 718.4 192.5 698.5 192.5z"
      p-id="7561" />
  </Svg>
)
