
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="pausecircle" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M512 0C229.2 0 0 229.2 0 512s229.2 512 512 512 512-229.2 512-512S794.8 0 512 0zM393 668c0 19.9-16.1 36-36 36l0 0c-19.9 0-36-16.1-36-36L321 356c0-19.9 16.1-36 36-36l0 0c19.9 0 36 16.1 36 36L393 668zM703 668c0 19.9-16.1 36-36 36l0 0c-19.9 0-36-16.1-36-36L631 356c0-19.9 16.1-36 36-36l0 0c19.9 0 36 16.1 36 36L703 668z"
      p-id="7532" />
  </Svg>
)
