
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="play" width={ props.width || 16 } height={ props.height || 16 } fill={ props.fill || "#666" }>
    <Path d="M512 2C229.8 2 1 230.8 1 513c0 282.2 228.8 511 511 511 282.2 0 511-228.8 511-511S794.2 2 512 2zM711.6 526.6 420.7 774.1c-4.2 3.7-9.3 5.4-14.3 5.4-10.8 0-21-7.6-21-19L385.4 265.4c0-11.4 10.2-19 21-19 5 0 10.1 1.6 14.3 5.4l290.9 247.5C720.1 506.8 720.1 519.1 711.6 526.6z"
      p-id="4719" />
  </Svg>
)
