
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="plus" width={ props.width || 16 } height={ props.height || 16 } fill={ props.fill || "#666" }>
    <Path d="M866.5 476 548 476 548 165.5c0-19.9-16.1-36-36-36l0 0c-19.9 0-36 16.1-36 36L476 476 164.5 476c-19.9 0-36 16.1-36 36l0 0c0 19.9 16.1 36 36 36L476 548l0 311.5c0 19.9 16.1 36 36 36l0 0c19.9 0 36-16.1 36-36L548 548l318.5 0c19.9 0 36-16.1 36-36l0 0C902.5 492.1 886.4 476 866.5 476z"
      p-id="8199" />
  </SvgContainer>
)
