
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="printer" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M392 752h240v72H392zM392 584h240v72H392zM888 248H768V136c0-39.8-32.2-72-72-72H328c-39.8 0-72 32.2-72 72v112H136c-39.8 0-72 32.2-72 72v304c0 39.8 32.2 72 72 72h120v192c0 39.8 32.2 72 72 72h368c39.8 0 72-32.2 72-72V696h120c39.8 0 72-32.2 72-72V320c0-39.8-32.2-72-72-72zM328 137c0-0.6 0.4-1 1-1h366c0.5 0 1 0.5 1 1v110c0 0.6-0.4 1-1 1H329c-0.5 0-1-0.5-1-1V137z m368 751H328V520h368v368z m192-264H768V520c0-39.8-32.2-72-72-72H328c-39.8 0-72 32.2-72 72v104H136V320h752v304zM820 388m-36 0a36 36 0 1 0 72 0 36 36 0 1 0-72 0Z"
      p-id="3760" />
  </SvgContainer>
)
