
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="profile" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M888 64H136c-39.8 0-72 32.2-72 72v752c0 39.8 32.2 72 72 72h752c39.8 0 72-32.2 72-72V136c0-39.8-32.2-72-72-72z m0 824H136V136h752v752z" p-id="1882" />
    <Path d="M420 740h312c19.9 0 36-16.1 36-36s-16.1-36-36-36H420c-19.9 0-36 16.1-36 36s16.1 36 36 36zM420 356h312c19.9 0 36-16.1 36-36s-16.1-36-36-36H420c-19.9 0-36 16.1-36 36s16.1 36 36 36zM420 548h312c19.9 0 36-16.1 36-36s-16.1-36-36-36H420c-19.9 0-36 16.1-36 36s16.1 36 36 36z"
      p-id="1883" />
    <Path d="M292 704m-36 0a36 36 0 1 0 72 0 36 36 0 1 0-72 0Z" p-id="1884" />
    <Path d="M292 320m-36 0a36 36 0 1 0 72 0 36 36 0 1 0-72 0Z" p-id="1885" />
    <Path d="M292 512m-36 0a36 36 0 1 0 72 0 36 36 0 1 0-72 0Z" p-id="1886" />
  </SvgContainer>
)
