
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="select1" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M888 64H136c-39.8 0-72 32.2-72 72v752c0 39.8 32.2 72 72 72h504c19.9 0 36-16.1 36-36s-16.1-36-36-36H136V136h752v504c0 19.9 16.1 36 36 36s36-16.1 36-36V136c0-39.8-32.2-72-72-72z"
      p-id="2888" />
    <Path d="M633.5 582.5l103.8-103.8c11.3-11.3 3.3-30.7-12.7-30.7H484c-19.9 0-36 16.1-36 36v240.5c0 16 19.4 24.1 30.7 12.7l103.8-103.8 188 188c7 7 16.2 10.5 25.5 10.5s18.4-3.5 25.5-10.5c14.1-14.1 14.1-36.9 0-50.9l-188-188z"
      p-id="2889" />
  </SvgContainer>
)
