
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp-compatible';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="sound" width={ props.width || 16 } height={ props.height || 16 } fill={ props.fill || "#666" }>
    <Path d="M464.3 165L231.1 320H65c-35.9 0-65 32.2-65 72v240c0 39.8 29.1 72 65 72h166.1l233.2 155c30.8 20.5 55.7 4.8 55.7-34.9V200c0-39.8-24.9-55.4-55.7-35zM448 762L257.4 632H72V392H257.3L448 265v497zM640 664c-19.9 0-36 16.1-36 36s16.1 36 36 36c123.7 0 224-100.3 224-224S763.7 288 640 288c-19.9 0-36 16.1-36 36s16.1 36 36 36c83.9 0 152 68.1 152 152s-68.1 152-152 152zM640 128c-19.9 0-36 16.1-36 36s16.1 36 36 36c172.3 0 312 139.7 312 312S812.3 824 640 824c-19.9 0-36 16.1-36 36s16.1 36 36 36c212.1 0 384-171.9 384-384S852.1 128 640 128z"
      p-id="2507" />
  </Svg>
)
