
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="stepbackward" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M759.3 76.3 327.9 431.6 327.9 132c0-19.9-16.1-36-36-36l0 0c-19.9 0-36 16.1-36 36l0 760c0 19.9 16.1 36 36 36l0 0c19.9 0 36-16.1 36-36L327.9 590.6l431.3 357.2c27.4 24.4 70.8 5 70.8-31.7L830 107.9C830 71.3 786.6 51.8 759.3 76.3z"
      p-id="9272" />
  </SvgContainer>
)
