
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="switcher" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M572 604H196c-19.9 0-36 16.1-36 36s16.1 36 36 36h376c19.9 0 36-16.1 36-36s-16.1-36-36-36zM696 328v624H72V328h624m0-72H72c-39.8 0-72 32.2-72 72v624c0 39.8 32.2 72 72 72h624c39.8 0 72-32.2 72-72V328c0-39.8-32.2-72-72-72zM952 0H359.7c-19.9 0-36 16.1-36 36s16.1 36 36 36H952v596c0 19.9 16.1 36 36 36s36-16.1 36-36V72c0-39.8-32.2-72-72-72zM824 128H164c-19.9 0-36 16.1-36 36s16.1 36 36 36h660v660c0 19.9 16.1 36 36 36s36-16.1 36-36V200c0-39.8-32.2-72-72-72z"
      p-id="4545" />
  </Svg>
)
