
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp-compatible';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="tablet1" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M824 0H200c-39.8 0-72 32.2-72 72v880c0 39.8 32.2 72 72 72h624c39.8 0 72-32.2 72-72V72c0-39.8-32.2-72-72-72zM542 960h-60c-19.9 0-34-14.3-34-32s14.1-32 34-32h60c19.9 0 34 14.3 34 32s-14.1 32-34 32z m282-129H200V72h624v759z"
      p-id="4021" />
  </Svg>
)
