
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="Trophy" width={ props.width || 16 } height={ props.height || 16 } fill={ props.fill || "#666" }>
    <Path d="M759.9 512h8.1c70.7 0 128-57.3 128-128V128H767.5c-4-36-34.5-64-71.5-64H328c-37.1 0-67.6 28-71.5 64H128v256c0 70.7 57.3 128 128 128h8.1C289.6 611.1 373 687 476 701.5V888H164c-19.9 0-36 16.1-36 36s16.1 36 36 36h696c19.9 0 36-16.1 36-36s-16.1-36-36-36H548V701.5C651.1 687 734.4 611.1 759.9 512z m8.1-312h56v184c0 30.9-25.1 56-56 56V200zM256 440c-30.9 0-56-25.1-56-56V200h56v240z m256 192c-101.6 0-184-82.4-184-184V136h368v312c0 101.6-82.4 184-184 184z"
      p-id="3151" />
  </Svg>
)
