
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp';
const { Path, default: SvgContainer } = Svg;
export default (props) => (
  <SvgContainer class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="wallet" width={ props.width || 16 } height={ props.height || 16 } fill={ props.fill || "#666" }>
    <Path d="M620 512m-36 0a36 36 0 1 0 72 0 36 36 0 1 0-72 0ZM952 128H72c-39.8 0-72 32.2-72 72v624c0 39.8 32.2 72 72 72h880c39.8 0 72-32.2 72-72V200c0-39.8-32.2-72-72-72z m0 440H520V456h432v112z m0-184H520c-39.8 0-72 32.2-72 72v112c0 39.8 32.2 72 72 72h432v184H72V200h880v184z"
      p-id="3267" />
  </SvgContainer>
)
