
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp-compatible';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="windowso" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M526.8 869l434 70.8L960.8 539.2l-434 0L526.8 869zM598.8 611.2l290 0 0 244-290-47.3L598.8 611.2zM526.8 138.2l0 328.7 434 0L960.8 66.1 526.8 138.2zM888.9 394.8l-290 0L598.9 199.2l290-48.1L888.9 394.8zM68.1 466.8 435 466.8 435 150.1 68.1 211 68.1 466.8zM140.1 272 363 235l0 159.8L140.1 394.8 140.1 272zM68.1 797.3 435 857.1 435 539.2 68.1 539.2 68.1 797.3zM140.1 611.2 363 611.2l0 161.2-222.9-36.3L140.1 611.2z"
      p-id="5299" />
  </Svg>
)
