
// Generated by 'transfrom'
/* eslint-disable */
import React from 'react';
import { Svg } from 'react-sketchapp-compatible';
const {Path} = Svg;
export default (props) => (
  <Svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" name="windows" width={ props.width || 16 } height={ props.height || 16 }
    fill={ props.fill || "#666" }>
    <Path d="M526.8 869 960.8 939.8 960.8 539.2 526.8 539.2ZM526.8 138.2 526.8 466.9 960.8 466.9 960.8 66.1ZM68.1 466.8 435 466.8 435 150.1 68.1 211ZM68.1 797.3 435 857.1 435 539.2 68.1 539.2Z"
      p-id="6053" />
  </Svg>
)
